import {
  ShoppingCart,
  Utensils,
  Car,
  Home,
  Plug,
  ShoppingBag,
  HeartPulse,
  Clapperboard,
  Plane,
  Repeat,
  GraduationCap,
  MoreHorizontal,
  Briefcase,
  Laptop,
  TrendingUp,
  Gift,
  Wallet,
  Landmark,
  Banknote,
  CreditCard,
  Smartphone,
  PiggyBank,
  CircleDollarSign,
  Target,
  Coffee,
  Dumbbell,
  Gamepad2,
  BookOpen,
  Baby,
  Dog,
  Gem,
  Wrench,
  Fuel,
  Bus,
  Train,
  Bike,
  Film,
  Music,
  Shirt,
  Scissors,
  Stethoscope,
  Pill,
  Umbrella,
  Building,
  Phone,
  Wifi,
  Tv,
  Zap,
  Droplet,
  Flame,
  Trash2,
  Palette,
  Camera,
  Ship,
  Hotel,
  Ticket,
  PartyPopper,
  Cake,
  Beer,
  Wine,
  Pizza,
  Apple,
  Leaf,
  Sun,
  Moon,
  Star,
  Circle,
  Tag,
  Receipt,
  Calculator,
  Coins,
  HandCoins,
  Users,
  User,
  School,
  Shield,
  Newspaper,
  Milk,
  Handshake,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  "shopping-cart": ShoppingCart,
  utensils: Utensils,
  car: Car,
  home: Home,
  plug: Plug,
  "shopping-bag": ShoppingBag,
  "heart-pulse": HeartPulse,
  clapperboard: Clapperboard,
  plane: Plane,
  repeat: Repeat,
  "graduation-cap": GraduationCap,
  "more-horizontal": MoreHorizontal,
  briefcase: Briefcase,
  laptop: Laptop,
  "trending-up": TrendingUp,
  gift: Gift,
  wallet: Wallet,
  landmark: Landmark,
  banknote: Banknote,
  "credit-card": CreditCard,
  smartphone: Smartphone,
  "piggy-bank": PiggyBank,
  "circle-dollar-sign": CircleDollarSign,
  target: Target,
  coffee: Coffee,
  dumbbell: Dumbbell,
  "gamepad-2": Gamepad2,
  "book-open": BookOpen,
  baby: Baby,
  dog: Dog,
  gem: Gem,
  wrench: Wrench,
  fuel: Fuel,
  bus: Bus,
  train: Train,
  bike: Bike,
  film: Film,
  music: Music,
  shirt: Shirt,
  scissors: Scissors,
  stethoscope: Stethoscope,
  pill: Pill,
  umbrella: Umbrella,
  building: Building,
  phone: Phone,
  wifi: Wifi,
  tv: Tv,
  zap: Zap,
  droplet: Droplet,
  flame: Flame,
  "trash-2": Trash2,
  palette: Palette,
  camera: Camera,
  ship: Ship,
  hotel: Hotel,
  ticket: Ticket,
  "party-popper": PartyPopper,
  cake: Cake,
  beer: Beer,
  wine: Wine,
  pizza: Pizza,
  apple: Apple,
  leaf: Leaf,
  sun: Sun,
  moon: Moon,
  star: Star,
  circle: Circle,
  tag: Tag,
  receipt: Receipt,
  calculator: Calculator,
  coins: Coins,
  "hand-coins": HandCoins,
  users: Users,
  user: User,
  school: School,
  shield: Shield,
  newspaper: Newspaper,
  milk: Milk,
  handshake: Handshake,
};

export const ICON_NAMES = Object.keys(ICONS);

export function getIcon(name: string): LucideIcon {
  return ICONS[name] ?? Circle;
}
